<?php

return [
    'profiles' => [
        // Permissions currently enforced in v1 Billing routes/gates.
        'implemented' => [
            'billing-invoices.view-audit-logs',
            'billing.invoices.create',
            'billing.invoices.read',
            'billing.invoices.issue',
            'billing.invoices.update-draft',
            'billing.invoices.cancel',
            'billing.invoices.void',
            'billing.payments.record',
            'billing.payments.view-history',
            'billing.payments.reverse',
            'billing.financial-controls.read',
            'billing.service-catalog.read',
            'billing.service-catalog.manage',
            'billing.service-catalog.manage-identity',
            'billing.service-catalog.manage-pricing',
            'billing.service-catalog.view-audit-logs',
            'billing.payer-contracts.read',
            'billing.payer-contracts.manage',
            'billing.payer-contracts.view-audit-logs',
            'billing.payer-contracts.manage-price-overrides',
            'billing.payer-contracts.view-price-override-audit-logs',
            'billing.payer-contracts.manage-authorization-rules',
            'billing.payer-contracts.view-authorization-audit-logs',
            'billing.integrations.payments.gateway',
            'billing.integrations.nhif.verify',
            'billing.integrations.nhif.submit',
            'billing.integrations.nhif.tariff-sync',
            'billing.integrations.nhif.remittance',
            'billing.integrations.sms.send',
            'billing.integrations.receipts.issue',
            'billing.payments.read',
            'billing.insurance.read',
            'billing.insurance.manage',
        ],

        // Rollout-ready Billing permission set for phased RBAC hardening.
        // Note: some permissions may be UI/process planned before route-level enforcement.
        'rollout_recommended' => [
            'billing.invoices.read',
            'billing.invoices.create',
            'billing.invoices.update-draft',
            'billing.invoices.issue',
            'billing.invoices.cancel',
            'billing.invoices.void',
            'billing.payments.record',
            'billing.payments.view-history',
            'billing.payments.reverse',
            'billing.financial-controls.read',
            'billing-invoices.view-audit-logs', // v1 legacy/current gate-backed ID
            'billing.service-catalog.read',
            'billing.service-catalog.manage',
            'billing.service-catalog.manage-identity',
            'billing.service-catalog.manage-pricing',
            'billing.service-catalog.view-audit-logs',
            'billing.payer-contracts.read',
            'billing.payer-contracts.manage',
            'billing.payer-contracts.view-audit-logs',
            'billing.payer-contracts.manage-price-overrides',
            'billing.payer-contracts.view-price-override-audit-logs',
            'billing.payer-contracts.manage-authorization-rules',
            'billing.payer-contracts.view-authorization-audit-logs',
            'billing.integrations.payments.gateway',
            'billing.integrations.nhif.verify',
            'billing.integrations.receipts.issue',
        ],
    ],

    'roles' => [
        'billing_cashier' => [
            'billing.invoices.read',
            'billing.invoices.create',
            'billing.invoices.update-draft',
            'billing.payments.record',
            'billing.payments.read',
            'billing.payments.view-history',
            'billing.service-catalog.read',
            'billing.payer-contracts.read',
            'billing.integrations.payments.gateway',
            'billing.integrations.nhif.verify',
            'billing.integrations.nhif.submit',
            'billing.integrations.receipts.issue',
            'billing.insurance.read',
        ],
        'billing_supervisor' => [
            'departments.read',
            'billing.invoices.read',
            'billing.invoices.create',
            'billing.invoices.update-draft',
            'billing.invoices.issue',
            'billing.invoices.cancel',
            'billing.invoices.void',
            'billing.payments.record',
            'billing.payments.read',
            'billing.payments.view-history',
            'billing.payments.reverse',
            'billing.financial-controls.read',
            'billing-invoices.view-audit-logs',
            'billing.service-catalog.read',
            'billing.service-catalog.manage-identity',
            'billing.service-catalog.manage-pricing',
            'billing.service-catalog.view-audit-logs',
            'billing.payer-contracts.read',
            'billing.payer-contracts.manage',
            'billing.payer-contracts.view-audit-logs',
            'billing.payer-contracts.manage-price-overrides',
            'billing.payer-contracts.view-price-override-audit-logs',
            'billing.payer-contracts.manage-authorization-rules',
            'billing.payer-contracts.view-authorization-audit-logs',
            'billing.integrations.payments.gateway',
            'billing.integrations.nhif.verify',
            'billing.integrations.nhif.submit',
            'billing.integrations.nhif.tariff-sync',
            'billing.integrations.nhif.remittance',
            'billing.integrations.sms.send',
            'billing.integrations.receipts.issue',
            'billing.insurance.read',
            'billing.insurance.manage',
        ],
        'finance_auditor' => [
            'billing.invoices.read',
            'billing.payments.view-history',
            'billing.financial-controls.read',
            'billing-invoices.view-audit-logs',
            'billing.service-catalog.read',
            'billing.service-catalog.view-audit-logs',
            'billing.payer-contracts.read',
            'billing.payer-contracts.view-audit-logs',
            'billing.payer-contracts.view-price-override-audit-logs',
            'billing.payer-contracts.view-authorization-audit-logs',
        ],
    ],
];
