<?php

return [
    'active' => env('AHS_COUNTRY_PROFILE', 'TZ'),

    'profiles' => [
        'TZ' => [
            'code' => 'TZ',
            'name' => 'Tanzania',
            'timezone' => 'Africa/Dar_es_Salaam',
            'currencyCode' => 'TZS',
            'languages' => ['en', 'sw'],
            'locales' => ['en_TZ', 'sw_TZ'],
            'patientAddressing' => [
                'regionLabel' => 'Region',
                'districtLabel' => 'District',
                'regionPlaceholder' => 'e.g. Dar es Salaam',
                'districtPlaceholder' => 'e.g. Ilala',
                'addressLabel' => 'Address',
                'addressPlaceholder' => 'Street, area, village, or landmark',
            ],
            'regulatory' => [
                'consentModel' => 'explicit',
                'auditLogRetentionYears' => 7,
                'dataResidencyPolicy' => 'approved-region-or-in-country',
                'requirePhiEncryptionAtRest' => true,
            ],
            'interoperability' => [
                'icd10' => true,
                'loinc' => true,
                'snomedCt' => 'licensed_when_available',
                'fhirApiVersioningRequired' => true,
            ],
            'billing' => [
                'vatEnabled' => true,
                'supportedPayers' => ['nhif', 'private'],
                'multiCurrencyAllowed' => true,
            ],
        ],
        'KE' => [
            'code' => 'KE',
            'name' => 'Kenya',
            'timezone' => 'Africa/Nairobi',
            'currencyCode' => 'KES',
            'languages' => ['en', 'sw'],
            'locales' => ['en_KE', 'sw_KE'],
            'patientAddressing' => [
                'regionLabel' => 'County',
                'districtLabel' => 'Sub-county / City',
                'regionPlaceholder' => 'e.g. Nairobi',
                'districtPlaceholder' => 'e.g. Westlands',
                'addressLabel' => 'Address',
                'addressPlaceholder' => 'Estate, area, village, or landmark',
            ],
            'regulatory' => [
                'consentModel' => 'explicit',
                'auditLogRetentionYears' => 7,
                'dataResidencyPolicy' => 'policy-driven',
                'requirePhiEncryptionAtRest' => true,
            ],
            'interoperability' => [
                'icd10' => true,
                'loinc' => true,
                'snomedCt' => 'licensed_when_available',
                'fhirApiVersioningRequired' => true,
            ],
            'billing' => [
                'vatEnabled' => true,
                'supportedPayers' => ['public', 'private'],
                'multiCurrencyAllowed' => true,
            ],
        ],
        'UG' => [
            'code' => 'UG',
            'name' => 'Uganda',
            'timezone' => 'Africa/Kampala',
            'currencyCode' => 'UGX',
            'languages' => ['en'],
            'locales' => ['en_UG'],
            'patientAddressing' => [
                'regionLabel' => 'Region',
                'districtLabel' => 'District / City',
                'regionPlaceholder' => 'e.g. Central Region',
                'districtPlaceholder' => 'e.g. Kampala',
                'addressLabel' => 'Address',
                'addressPlaceholder' => 'Village, parish, road, or landmark',
            ],
            'regulatory' => [
                'consentModel' => 'explicit',
                'auditLogRetentionYears' => 7,
                'dataResidencyPolicy' => 'policy-driven',
                'requirePhiEncryptionAtRest' => true,
            ],
            'interoperability' => [
                'icd10' => true,
                'loinc' => true,
                'snomedCt' => 'licensed_when_available',
                'fhirApiVersioningRequired' => true,
            ],
            'billing' => [
                'vatEnabled' => true,
                'supportedPayers' => ['public', 'private'],
                'multiCurrencyAllowed' => true,
            ],
        ],
        'RW' => [
            'code' => 'RW',
            'name' => 'Rwanda',
            'timezone' => 'Africa/Kigali',
            'currencyCode' => 'RWF',
            'languages' => ['en', 'fr'],
            'locales' => ['en_RW', 'fr_RW'],
            'patientAddressing' => [
                'regionLabel' => 'Province',
                'districtLabel' => 'District',
                'regionPlaceholder' => 'e.g. Kigali City',
                'districtPlaceholder' => 'e.g. Gasabo',
                'addressLabel' => 'Address',
                'addressPlaceholder' => 'Sector, cell, village, or landmark',
            ],
            'regulatory' => [
                'consentModel' => 'explicit',
                'auditLogRetentionYears' => 7,
                'dataResidencyPolicy' => 'policy-driven',
                'requirePhiEncryptionAtRest' => true,
            ],
            'interoperability' => [
                'icd10' => true,
                'loinc' => true,
                'snomedCt' => 'licensed_when_available',
                'fhirApiVersioningRequired' => true,
            ],
            'billing' => [
                'vatEnabled' => true,
                'supportedPayers' => ['public', 'private'],
                'multiCurrencyAllowed' => true,
            ],
        ],
    ],
];
