<?php

return [
    'platform-super-admin' => [
        'code' => 'PLATFORM.SUPER.ADMIN',
        'name' => 'System Administrator',
        'description' => 'Ministry of Health ICT. Full platform access across all facilities.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [],
    ],

    'platform-user-admin' => [
        'code' => 'PLATFORM.USER.ADMIN',
        'name' => 'Platform User Administrator',
        'description' => 'Manages user accounts and facility assignments across the platform.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [],
    ],

    'platform-rbac-admin' => [
        'code' => 'PLATFORM.RBAC.ADMIN',
        'name' => 'Platform RBAC Administrator',
        'description' => 'Manages roles, permissions, and access policies across the platform.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [],
    ],

    'platform-subscription-admin' => [
        'code' => 'PLATFORM.SUBSCRIPTION.ADMIN',
        'name' => 'Subscription Administrator',
        'description' => 'Manages facility subscriptions, plans, and entitlements.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [],
    ],

    'clinical-officer' => [
        'code' => 'CLINICAL.GENERAL',
        'name' => 'Clinical Officer',
        'description' => 'Diploma-level clinician. Main clinical staff at dispensaries and health centres.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'admissions.read',
            'medical.records.read', 'medical.records.create',
            'laboratory.access',
            'pharmacy.access',
            'patient.demographics.update',
            'patient.medications.manage',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'medical.records.amend',
            'lab.order',
            'medication.prescribe',
            'imaging.order',
            'laboratory.orders.read',
            'pharmacy.orders.read',
            'radiology.orders.read',
        ],
    ],

    'medical-officer' => [
        'code' => 'CLINICAL.PHYSICIAN',
        'name' => 'Medical Officer',
        'description' => 'Medical degree holder. Works at hospitals and health centres.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'admissions.read', 'admissions.create',
            'medical.records.read', 'medical.records.create',
            'laboratory.access', 'pharmacy.access',
            'patient.demographics.update',
            'patient.allergies.manage',
            'patient.medications.manage',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'medical.records.amend',
            'medical.records.attest',
            'lab.order',
            'medication.prescribe',
            'imaging.order',
            'admissions.update-status',
            'laboratory.orders.read',
            'pharmacy.orders.read',
            'radiology.orders.read',
        ],
    ],

    'surgeon' => [
        'code' => 'CLINICAL.SURGEON',
        'name' => 'Surgeon',
        'description' => 'Surgical specialist. Performs operations and post-op care.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'admissions.read', 'admissions.create',
            'medical.records.read', 'medical.records.create',
            'laboratory.access', 'pharmacy.access',
            'patient.demographics.update',
            'patient.allergies.manage',
            'patient.medications.manage',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'medical.records.amend',
            'lab.order',
            'medication.prescribe',
            'imaging.order',
            'theatre.procedures.read',
            'theatre.procedures.create',
            'theatre.procedures.update-status',
            'laboratory.orders.read',
            'pharmacy.orders.read',
            'radiology.orders.read',
        ],
    ],

    'nurse-officer' => [
        'code' => 'CLINICAL.NURSE',
        'name' => 'Nurse Officer',
        'description' => 'Registered Nurse. Provides bedside care, medication administration, patient monitoring.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'appointments.read',
            'admissions.read',
            'medical.records.read',
            'inpatient.ward.read',
            'inpatient.ward.create-task',
            'inpatient.ward.update-task-status',
            'inpatient.ward.create-care-plan',
            'inpatient.ward.update-care-plan',
            'patient.vitals.record',
            'lab.sample.collect',
            'service.requests.create',
            'service.requests.read',
        ],
    ],

    'nurse-midwife' => [
        'code' => 'CLINICAL.NURSE.MIDWIFE',
        'name' => 'Nurse Midwife',
        'description' => 'Specialised in maternal and child health. Antenatal, delivery, postnatal care.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'lab.sample.collect',
        ],
    ],

    'lab-technologist' => [
        'code' => 'LAB.STAFF',
        'name' => 'Laboratory Technologist',
        'description' => 'Performs lab tests, enters results. Cannot order tests.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'laboratory.access',
            'laboratory.orders.read',
            'lab.sample.collect',
            'lab.sample.reject',
            'lab.test.perform',
            'lab.result.enter',
        ],
    ],

    'lab-supervisor' => [
        'code' => 'LAB.SUPERVISOR',
        'name' => 'Chief Laboratory Technologist',
        'description' => 'Supervises lab staff. Verifies and releases results.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'laboratory.access',
            'laboratory.orders.read',
            'lab.sample.collect',
            'lab.sample.reject',
            'lab.test.perform',
            'lab.result.enter',
            'lab.result.verify',
            'lab.result.release',
            'laboratory.orders.audit-logs.view',
        ],
    ],

    'lab-manager' => [
        'code' => 'LAB.MANAGER',
        'name' => 'Laboratory Manager',
        'description' => 'Manages laboratory operations, quality control, and staffing.',
        'access_level' => 'manage',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'laboratory.access',
            'laboratory.orders.read',
            'lab.sample.collect',
            'lab.sample.reject',
            'lab.test.perform',
            'lab.result.enter',
            'lab.result.verify',
            'lab.result.release',
            'laboratory.orders.audit-logs.view',
        ],
    ],

    'dispenser' => [
        'code' => 'PHARMACY.STAFF',
        'name' => 'Dispenser',
        'description' => 'Diploma pharmaceutical technician. Dispenses medications under supervision.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'pharmacy.access',
            'pharmacy.orders.read',
            'medication.dispense',
        ],
    ],

    'pharmacist' => [
        'code' => 'PHARMACY.SUPERVISOR',
        'name' => 'Pharmacist-in-Charge',
        'description' => 'Degree pharmacist. Verifies prescriptions, manages pharmacy.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'pharmacy.access',
            'pharmacy.orders.read',
            'pharmacy.orders.verify-dispense',
            'pharmacy.orders.manage-policy',
            'pharmacy.orders.reconcile',
            'medication.dispense',
            'dispense.cancel',
            'pharmacy.orders.audit-logs.view',
        ],
    ],

    'radiographer' => [
        'code' => 'RADIOLOGY.STAFF',
        'name' => 'Radiographer',
        'description' => 'Performs X-ray and imaging procedures.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'imaging.access',
            'imaging.order',
            'imaging.perform',
            'imaging.result.enter',
        ],
    ],

    'radiographer-senior' => [
        'code' => 'RADIOLOGY.SUPERVISOR',
        'name' => 'Senior Radiographer',
        'description' => 'Supervises radiology staff. Verifies imaging reports.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'imaging.access',
            'imaging.order',
            'imaging.perform',
            'imaging.result.enter',
            'imaging.result.verify',
            'radiology.orders.audit-logs.view',
        ],
    ],

    'cashier' => [
        'code' => 'FINANCE.CASHIER',
        'name' => 'Cashier',
        'description' => 'Receives payments, issues receipts, manages daily cash.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'billing.access',
            'billing.invoices.read',
            'billing.payments.record',
            'billing.payments.view-history',
            'billing.refunds.create',
            'billing.refunds.read',
            'pos.registers.read',
            'pos.sessions.read',
            'pos.sales.read',
            'pos.sales.create',
        ],
    ],

    'receptionist' => [
        'code' => 'ADMIN.REGISTRATION',
        'name' => 'Health Records Officer',
        'description' => 'Manages patient registration, appointments, front desk.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read', 'patients.create',
            'patient.demographics.update',
            'appointments.read', 'appointments.create',
            'appointment.reschedule', 'appointment.cancel',
            'appointment.check-in',
            'service.requests.create',
            'service.requests.read',
        ],
    ],

    'hospital-admin' => [
        'code' => 'ADMIN.FACILITY',
        'name' => 'Hospital Administrator',
        'description' => 'Manages facility operations, staffing, and administration.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read', 'patients.create', 'patient.demographics.update',
            'patients.update-status',
            'appointments.read', 'appointments.create', 'appointment.reschedule',
            'medical.records.read', 'medical.records.archive',
            'admissions.read', 'admissions.create', 'admissions.update',
            'laboratory.access', 'pharmacy.access', 'imaging.access',
            'staff.read', 'staff.create',
            'staff.employment.update', 'staff.status.update',
            'staff.documents.read', 'staff.documents.create',
            'staff.documents.verify',
            'staff.credentialing.read', 'staff.credentialing.verify',
            'departments.read', 'departments.create', 'departments.update',
            'platform.clinical-catalog.read',
            'platform.resources.read',
            'inventory.procurement.read',
        ],
    ],

    'nutritionist' => [
        'code' => 'ALLIED.NUTRITIONIST',
        'name' => 'Nutritionist',
        'description' => 'Manages therapeutic feeding, malnutrition, and dietary counseling.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'medical.records.read',
            'medical.records.create',
            'medical.records.draft.update',
        ],
    ],

    'counselor' => [
        'code' => 'ALLIED.COUNSELOR',
        'name' => 'Counselor',
        'description' => 'Provides HIV testing counseling, adherence support, psychosocial support.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'medical.records.read',
            'medical.records.create',
            'medical.records.draft.update',
        ],
    ],

    'community-health-worker' => [
        'code' => 'ALLIED.COMMUNITY.HEALTH.WORKER',
        'name' => 'Community Health Worker',
        'description' => 'Conducts home visits, defaulter tracing, health education, and outreach.',
        'access_level' => 'view',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'patients.create',
            'appointments.read',
        ],
    ],

    'medical-attendant' => [
        'code' => 'SUPPORT.MEDICAL.ATTENDANT',
        'name' => 'Medical Attendant',
        'description' => 'Patient hygiene, bed-making, linen, cleaning, basic patient care.',
        'access_level' => 'view',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inpatient.ward.read',
            'inpatient.ward.create-task',
            'inpatient.ward.update-task-status',
        ],
    ],

    'health-secretary' => [
        'code' => 'SUPPORT.HEALTH.SECRETARY',
        'name' => 'Health Secretary',
        'description' => 'Front desk, document management, appointment scheduling, referrals.',
        'access_level' => 'view',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'appointments.read', 'appointments.create',
            'service.requests.create',
            'service.requests.read',
        ],
    ],

    'dental-officer' => [
        'code' => 'CLINICAL.DENTAL.OFFICER',
        'name' => 'Dental Officer',
        'description' => 'Dental exams, extractions, fillings, oral health education.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'appointments.read', 'appointments.create',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'medical.records.draft.update',
            'medical.records.finalize',
        ],
    ],

    'emergency-nurse' => [
        'code' => 'CLINICAL.EMERGENCY',
        'name' => 'Casualty Nurse',
        'description' => 'Emergency and casualty care, triage, acute patient management.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'appointments.read',
            'admissions.read',
            'medical.records.read',
            'emergency.triage.create',
            'emergency.triage.update',
            'emergency.triage.update-status',
            'emergency.triage.read',
            'patient.vitals.record',
            'lab.sample.collect',
        ],
    ],

    'accountant' => [
        'code' => 'FINANCE.OFFICER',
        'name' => 'Accountant',
        'description' => 'Handles accounts, reconciliations, financial reporting.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'billing.access',
            'billing.invoices.read',
            'billing.financial-controls.read',
            'billing.payments.record',
            'billing.payments.view-history',
            'billing.refunds.read',
        ],
    ],

    'finance-manager' => [
        'code' => 'FINANCE.CONTROLLER',
        'name' => 'Finance Manager',
        'description' => 'Oversees financial operations, approvals, audits.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'billing.access',
            'billing.invoices.read',
            'billing.invoices.create',
            'billing.invoices.void',
            'billing.financial-controls.read',
            'billing.payments.record',
            'billing.payments.reverse',
            'billing.payments.view-history',
            'billing.refunds.read',
            'billing.refunds.create',
            'billing.refunds.approve',
        ],
    ],

    'insurance-officer' => [
        'code' => 'FINANCE.CLAIMS',
        'name' => 'Insurance Claims Officer',
        'description' => 'Processes insurance claims, verifications, and reconciliations.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'billing.access',
            'billing.invoices.read',
            'billing.payments.view-history',
            'patients.insurance.read',
            'patients.insurance.manage',
            'patients.insurance.verify',
        ],
    ],

    'storekeeper' => [
        'code' => 'INVENTORY.STAFF',
        'name' => 'Storekeeper',
        'description' => 'Manages stock, inventory movements, and warehouse operations.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inventory.view-own-items',
            'inventory.view-requisition-own',
            'inventory.view-warehouse-own-department',
            'inventory.create-requisition-own-department',
        ],
    ],

    'senior-storekeeper' => [
        'code' => 'INVENTORY.SUPERVISOR',
        'name' => 'Senior Storekeeper',
        'description' => 'Supervises store operations, approves requisitions.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inventory.view-own-items',
            'inventory.view-department-items',
            'inventory.view-requisition-own',
            'inventory.view-warehouse-own-department',
            'inventory.create-requisition-own-department',
            'inventory.approve-requisition-own-department',
            'inventory.execute-warehouse-transfer-own-department',
        ],
    ],

    'procurement-officer' => [
        'code' => 'INVENTORY.MANAGER',
        'name' => 'Procurement Officer',
        'description' => 'Manages procurement, supplier relationships, and budget controls.',
        'access_level' => 'manage',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inventory.view-own-items',
            'inventory.view-department-items',
            'inventory.view-requisition-own',
            'inventory.view-warehouse-own-department',
            'inventory.create-requisition-own-department',
            'inventory.create-requisition-cross-department',
            'inventory.approve-requisition-own-department',
            'inventory.manage-warehouse-own-department',
            'inventory.execute-warehouse-transfer-own-department',
            'inventory.authorize-warehouse-transfer-receiving-department',
            'inventory.dispose-items-own-department',
        ],
    ],

    'theatre-nurse' => [
        'code' => 'THEATRE.STAFF',
        'name' => 'Theatre Nurse',
        'description' => 'Assists in surgical procedures, manages theatre resources.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'theatre.procedures.read',
            'theatre.procedures.create',
        ],
    ],

    'theatre-nurse-in-charge' => [
        'code' => 'THEATRE.SUPERVISOR',
        'name' => 'Theatre Nurse-in-Charge',
        'description' => 'Supervises theatre operations, schedules procedures.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'theatre.procedures.read',
            'theatre.procedures.create',
            'theatre.procedures.update',
            'theatre.procedures.update-status',
            'theatre.procedures.manage-resources',
        ],
    ],

    'theatre-manager' => [
        'code' => 'THEATRE.MANAGER',
        'name' => 'Theatre Manager',
        'description' => 'Manages theatre department, resource planning, and quality.',
        'access_level' => 'manage',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'theatre.procedures.read',
            'theatre.procedures.create',
            'theatre.procedures.update',
            'theatre.procedures.update-status',
            'theatre.procedures.manage-resources',
            'theatre.procedures.view-resource-audit-logs',
        ],
    ],
];
